name: JSON to YAML

on:
  push:
    branches:
      - main  # or specify another branch
  pull_request:
  workflow_dispatch:  # Adds a manual trigger option

jobs:
  convert-json-to-yml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify Python version

    - name: List files in the repository
      run: ls -R  # Lists all files and directories recursively

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Install PyYAML for JSON to YAML conversion

    - name: Run JSON to YAML conversion
      run: |
        python json_to_yml.py
      env:
        JSON_FILE_PATH: 'tests/sample.json'  # Path to the JSON file
        YAML_FILE_PATH: 'tests/json_to_yml.yaml'    # Path to save the YAML file
